Close config file handle on error.
COVESA/dlt-daemon pull request #613
Opened 2024-03-27 13:12 UTC by vladimir-aurora

If parsing of config file fails, close the file before returning an error.

2024-04-29 11:59 UTC, minminlittleshrimp commented
Approved, file should be closed correctly.
Hello @michael-methner , kindly check and merge!

2024-04-29 12:07 UTC, minminlittleshrimp requested changes
Kindly fclose pFile for min size buffer check fail at line 577.

2024-05-08 09:34 UTC, minminlittleshrimp commented
Hello @vladimir-aurora 
Kindly update the patch for review and merge.
Thank you a lots

2024-05-09 09:34 UTC, vladimir-aurora commented
The patch has been updated to include the changes proposed by @minminlittleshrimp

2024-05-09 10:15 UTC, minminlittleshrimp approved these changes

2024-05-09 10:47 UTC, merged